<div class="row">
    <div class="col-md-8">
        <form name="referral-form" method="post" id="referral-form" class="form"
            action="<?php echo $this->getFormAction(); ?>"
            data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
            data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset">
                <legend class="legend"><span><?= $block->escapeHtmlAttr(__('Referral Information')) ?></span>
                </legend>
                <fieldset class="fieldset row">
                    <div class="fields col-md-6">
                        <div class="field field-name-firstname required">
                            <label class="label" for="firstname"><span><?= $block->escapeHtmlAttr(__('First Name')) ?></span></label>
                            <div class="control">
                                <input name="firstname" id="firstname" title="First Name" value="" class="input-text" type="text" data-validate="{required:true, 'validate-alpha':true}">
                            </div>
                        </div>
                        <div class="field field field-name-lastname required required">
                            <label class="label" for="lastname"><span><?= $block->escapeHtmlAttr(__('Last Name')) ?></span></label>
                            <div class="control">
                                <input name="lastname" id="lastname" title="Last Name" value="" class="input-text" type="text" data-validate="{required:true, 'validate-alpha':true}">
                            </div>
                        </div>
                        <div class="field email required">
                            <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                            <div class="control">
                                <input name="email" value="" id="email" type="email" class="input-text" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
                            </div>
                        </div>
                        <div class="field phone required">
                            <label class="label" for="phone"><span><?= $block->escapeHtmlAttr(__('Telephone')) ?></span></label>
                            <div class="control">
                                <input name="phone" id="phone" title="Phone" value="" class="input-text" type="text" data-validate="{required:true, 'validate-digits':'true'}">
                            </div>
                        </div>
                    </div>
                </fieldset>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action submit primary" title="Save"><span><?= $block->escapeHtmlAttr(__('Save')) ?></span></button>
                </div>
            </div>
        </form>
    </div>
</div>

