<?php

/** @var $block \Wolfsellers\Referral\Block\Account\Dashboard\Form */
?>
<?php $referral = $block->getOrCreateReferral(); ?>
<form class="referral-form" action="<?= $escaper->escapeUrl($block->getFormAction()) ?>" method="post"
    id="referral-form" enctype="multipart/form-data"
    data-hasrequired="<?= $escaper->escapeHtmlAttr(__('* Required Fields')) ?>" data-mage-init='{"validation":{}}'>
    <input type="hidden" id="entity_id" name="entity_id" value="<?= $referral->getId() ?>" />
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $escaper->escapeHtml(__('Referral Information')) ?></span></legend><br>
        <div class="field field-firstname required">
            <label class="label" for="firstname"><span><?= $block->escapeHtmlAttr(__('First Name')) ?></span></label>
            <div class="control">
                <input name="firstname" id="firstname" title="First Name" value="<?= $referral->getFirstName() ?>" class="input-text" type="text"
                    data-validate="{required:true, 'validate-alpha':true}">
            </div>
        </div>
        <div class="field field field-lastname required required">
            <label class="label" for="lastname"><span><?= $block->escapeHtmlAttr(__('Last Name')) ?></span></label>
            <div class="control">
                <input name="lastname" id="lastname" title="Last Name" value="<?= $referral->getLastName() ?>" class="input-text" type="text"
                    data-validate="{required:true, 'validate-alpha':true}">
            </div>
        </div>
        <div class="field email required">
            <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input name="email" value="<?= $referral->getEmail() ?>" id="email" type="email" class="input-text"
                    title="<?= $block->escapeHtmlAttr(__('Email')) ?>" data-mage-init='{"mage/trim-input":{}}'
                    data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>
        <div class="field phone required">
            <label class="label" for="phone"><span><?= $block->escapeHtmlAttr(__('Telephone')) ?></span></label>
            <div class="control">
                <input name="phone" id="phone" title="Phone" value="<?= $referral->getPhone() ?>" class="input-text" type="text"
                    data-validate="{required:true, 'validate-digits':'true'}">
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action save primary">
                <span><?= $escaper->escapeHtml(__('Save')) ?></span>
            </button>
        </div>
        <div class="secondary">
            <a class="action secondary" href="<?= $escaper->escapeUrl($block->getBackUrl()) ?>">
                <span><?= $escaper->escapeHtml(__('Go back')) ?></span>
            </a>
        </div>
    </div>
</form>
